### ISSUE TITLE
Database Driver Issues

### ISSUE THREAD

**Issue by Mamadou99** [gammu/gammu#157]
Hi Everybody , i'm using the huawei ec156 for gammu. I have configured gammurc and gammu --identify is working . I've installed gammuSMSD too .
But :
- It tells me :"Error starting gammuSMSD service" when i do "gammu-smsd -s -c smsdrc n gammuSMSD"
- when i do "gammu-smsd -c smsdrc" it tells me :
Log filename is smsdlog
"gammu-smsd[7236]: Unknown DB Driver
Failed to read config: Unknown error."
Here is my smsdrc configuration : 
[smsd]
service = sql
PIN = 1234
logfile = smsdlog
debuglevel = 0
user = root
password =
pc = localhost
database = degloubin
driver = native_mysql

I'm using windows and mysql.
I wanted to know where are the problems.
Thanks !

**Comment by Armagetron** [comment]
Have you build Gammu for Windows yourself?

**Comment by nijel** [comment]
Probably the db driver is not compiled in, what is output of ``gammu-smsd -v``?

**Comment by Mamadou99** [comment]
Thanks For the answer. I use Gammu For Windows, the one downloadable on the website.
This is the output of gammu-smsd -v :
" Gammu-smsd version 1.33.0
Built 11:54:08 on May 29 2013 using GCC 4.7, MinGW 3.11
Compiled in features:
OS support:
  - WINDOWS_SERVICE
  - GETOPT
  - GETOPT_LONG
  - EVENT_LOG
Backend services:
  - NULL
  - FILES
  - ODBC "
Thanks Again

**Comment by Armagetron** [comment]
You have to install the MySQL ODBC driver and change the driver to obdc, then this build should work with MySQL on Windows.

Your other option is to build gammu yourself with the appropriate mysql driver.

**Comment by Mamadou99** [comment]
I saw that building gammu is with Cmake, but how to build it with a mysql driver ?
- I already have mysql in my computer
- I tried to compile the source version but there was a lot of errors. If cygwin is easier, i would really like to know the steps.
Is it possible to add mysql as a backend service with the windows version of gammu ?

Excuse me for responding very late it's because i didn't have satisfying results in my settings and i was hesitating about "bothering" you again... Sorry again

**Comment by Armagetron** [comment]
First of all, I assume that you are using Visual Studio to build gammu on Windows. Open the Developer Command Prompt (Start menu, Visual Studio, Tools).

You got 2 options:
1) You can try installing the MySQL ODBC driver and talk to MySQL using ODBC. You can find the instructions for the setup here: http://dev.mysql.com/doc/connector-odbc/en/

ODBC support comes with Visual Studio and is present in your current build. The connector should work fine but needs to be separately installed (like an addon for mysql so that the server speaks this protocol).

2) You can build gammu with the mysql library. Assume that mysql is installed in some folder (C:\mysql for example). Then you need to tell cmake where to find the library and include dir. To do so, invoke cmake from your build dir as follows:
```
C:\gammu\build>cmake.exe -DMYSQL_INCLUDE_DIR=C:\mysql\include -DMYSQL_LIBRARIES=C:\mysql\lib\libmysql.lib ..
```
Sadly, the lib depends on the dll. So you have to make sure, that the dll is within your PATH. I hope that helps.
Don't hesitate to ask!
