### ISSUE TITLE
[Database] Add IMSI to 'phones' table

### ISSUE THREAD

**Issue by JHGitty** [gammu/gammu#166]
The sql database contains the table ``phones`` for all current phones.

1. There is already a field ``IMEI`` but the field ``IMSI`` is missing.
2. There is no field ``PhoneNumber``.

**Comment by nijel** [comment]
As for the phone number it's impossible to get from most of modems...

**Comment by JHGitty** [comment]
Ok, but as I see the IMSI is sometimes available. I think it should be written to the database if it is available because it could be a nice feature.

**Comment by nijel** [comment]
Indeed IMEI/IMSI are usually available.

**Comment by antonero** [comment]
Also I have to create another table to insert this useful information because in our scenario with many /dev/gsmmodem(X) is hard to associate and count daily messages, so we have to write a cron script to verify info consistence, but in case of reset we need to change SMSD config file to associate right phoneID manually.
