### ISSUE TITLE
how to upgrade 1.4.0 --> 1.41

### ISSUE THREAD

**Issue by Fiftiz** [gammu/gammu#507]
Hello, I installed with `sudo apt-get install gammu gammu-smsd` , the package. but it's the 1.40 version. how i can upgrade on 1.41 ? the SR memory problem is resolve with this version ?

**Comment by svetlemodry** [comment]
On what operating system? Ubuntu seems to be having [v1.40](https://packages.ubuntu.com/search?keywords=gammu&searchon=names&suite=eoan&section=all) as the latest version available from their [universe] repository as of now.

**Comment by Fiftiz** [comment]
I use Rasbian, but after ckeck I think 1.41 = 1.40.0-1

**Comment by svetlemodry** [comment]
Looks like [Raspbian](http://archive.raspbian.org/raspbian/pool/main/g/gammu/) does not offer the latest version yet. The 1.40.0-1 package is available since March as per the time stamp and the version does not fit, so it's unlikely the latest stable gammu release.
I presume you could try to find out who maintains the gammu package for Raspbian and ask them for an update.

**Comment by Fiftiz** [comment]
ok thank you very much, because i have a problem with :` Ignoring incoming SMS info as not a Status Report in SR memory` in my log.  Ramdomly I received the sms, but often no :(
