### ISSUE TITLE
Gammu 1.33 fail with Wavecom Fastrack M1306B using USB

### ISSUE THREAD

**Issue by xtradi** [gammu/gammu#82]
If i try to run gammu i get this error message
>Fri 2015/01/02 10:47:20 gammu-smsd[844]: SQL failure: 2
>Fri 2015/01/02 10:47:20 gammu-smsd[844]: Error writing to database (SMSDSQL_SaveInboxSMS)
>Fri 2015/01/02 10:47:20 gammu-smsd[844]: Error processing SMS: Unknown error. (UNKNOWN[27])
>Fri 2015/01/02 10:47:31 gammu-smsd[844]: Read 1 messages
>Fri 2015/01/02 10:47:31 gammu-smsd[844]: SQLExecDirect failed, Code = -1, ODBC diagnostics:
>Fri 2015/01/02 10:47:31 gammu-smsd[844]: HY000:1:1292:[MySQL][ODBC 5.1 Driver][mysqld-5.6.22-log]Incorrect datetime value: '{ ts '2013-12-21 03:42:19' }' for column 'ReceivingDateTime' at row 1

i'm using Gammu 1.33 with MySQL 5.6 On windows 8.1 64 bit.

I can't use native mysql driver and already try using mysql connection 5.3, 5.1 for 32bit and 64bit.

**Comment by nijel** [comment]
Use ``sql=mysql`` in the smsd configuration. See documentaiton for more information: http://wammu.eu/docs/manual/smsd/config.html#option-SQL

**Comment by cheanizer** [comment]
hello, I am still facing this problem. with Gammu smsd config 
[gammu]
port = com5
connection = at115200
[smsd]
service = sql
sql = mysql
driver = odbc
PIN = 1234
logfile = smsdlog
debuglevel = 255
# Database backends congfiguration
host = mysql_odbc_ansi
user = root
password = ####
# pc = localhost
database = smscenter

connection to modem is ok, the only problem is ODBC driver triying to insert to mysql database. 
i have stuck for a view days and the solution is downgrade gammu to  1.32.0 so I can user mysql_native as driver and works as espected. 
But Downgrade gammu is not recomended solution because lack of support can help if something happen. 
here my machine specification:
1. OS windows 10.
2. ODBC driver v. 8.0.19 64 bit
3. mysql version 5.7.24
